# Generated by Django 5.2.4 on 2025-12-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0003_symptom_age_symptom_description_symptom_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
