# Generated by Django 5.2.4 on 2025-12-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0004_symptom_ai_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
